### PR TITLE
Update Quick_Links.md

### PR DESCRIPTION
**Pull request by Acid-Override**
Fixed typo and update UBlang to specify for Team Captains only.

### CODE REVIEW

**Comment by PeterNerlich** [comment]
@Acid-Override Nice!

**Review by PeterNerlich — CHANGES_REQUESTED** [review]
Looks good. Just minor changes, it seems. One request: remove protocol (`https://`) from links → `[t.me/...](https://t.me/...)`

**Comment by Acid-Override** [comment]
Take that!

**Review by PeterNerlich — APPROVED** [review]

**Comment by Acid-Override** [comment]
MERGE IT !  MERGE IT!  MERGE IT   :)  

lol

**Pull request merged**
